package com.solmit.entidad;
// Generated 15/06/2017 06:25:41 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetallePedidoId generated by hbm2java
 */
@Embeddable
public class DetallePedidoId implements java.io.Serializable {

	private int idDetallePedido;
	private int idPedido;

	public DetallePedidoId() {
	}

	public DetallePedidoId(int idDetallePedido, int idPedido) {
		this.idDetallePedido = idDetallePedido;
		this.idPedido = idPedido;
	}

	@Column(name = "id_detalle_pedido", nullable = false)
	public int getIdDetallePedido() {
		return this.idDetallePedido;
	}

	public void setIdDetallePedido(int idDetallePedido) {
		this.idDetallePedido = idDetallePedido;
	}

	@Column(name = "id_pedido", nullable = false)
	public int getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(int idPedido) {
		this.idPedido = idPedido;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetallePedidoId))
			return false;
		DetallePedidoId castOther = (DetallePedidoId) other;

		return (this.getIdDetallePedido() == castOther.getIdDetallePedido())
				&& (this.getIdPedido() == castOther.getIdPedido());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDetallePedido();
		result = 37 * result + this.getIdPedido();
		return result;
	}

}
