package com.solmit.entidad;
// Generated 15/06/2017 06:25:41 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetallePedido generated by hbm2java
 */
@Entity
@Table(name = "detalle_pedido", catalog = "tienda")
public class DetallePedido implements java.io.Serializable {

	private DetallePedidoId id;
	private Pedido pedido;
	private Producto producto;
	private Double precio;
	private Integer cantidad;

	public DetallePedido() {
	}

	public DetallePedido(DetallePedidoId id, Pedido pedido, Producto producto) {
		this.id = id;
		this.pedido = pedido;
		this.producto = producto;
	}

	public DetallePedido(DetallePedidoId id, Pedido pedido, Producto producto, Double precio, Integer cantidad) {
		this.id = id;
		this.pedido = pedido;
		this.producto = producto;
		this.precio = precio;
		this.cantidad = cantidad;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDetallePedido", column = @Column(name = "id_detalle_pedido", nullable = false)),
			@AttributeOverride(name = "idPedido", column = @Column(name = "id_pedido", nullable = false)) })
	public DetallePedidoId getId() {
		return this.id;
	}

	public void setId(DetallePedidoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pedido", nullable = false, insertable = false, updatable = false)
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_producto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "precio", precision = 22, scale = 0)
	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

}
